#!/bin/bash

# Start mailpit:
mailpit &

# If .env exists, export the .env variables.
if [[ -f .env ]]; then
	export $(cat .env | xargs)
fi

# Devmode things.
export SLOG_DEBUG=1 UWECECA_DEVELOPMENT=1

go run cmd/uwececa/main.go
